# This is a basic workflow to help you get started with Actions

name: Publish_blog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "blog-src" ]
  pull_request:
    branches: [ "blog-src" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "puslish"
  puslish:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # using the latest ubuntu as build and deploy env

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout codes
      uses: actions/checkout@v3

    - name: Setup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install hexo dependencies
      run: | 
        npm install -g hexo-cli
        npm install
    
    - name: Build and Generate files
      run: | 
        hexo clean
        hexo generate

    - name: Deploy Hexo Blog
      env: 
        GITHUB_REPO : github.com/zhaoyun4411/zhaoyun4411.github.io
      run: | 
        cd ./public && git init && git add .
        git config user.name "yun.zhao"
        git config user.email "2294583704@qq.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" main:main
        git push --force --quiet "https://RoYFbFDSfM:${{ secrets.CODING_TOKEN }}@$CODING_REPO" main:main
        git push --force --quiet "https://yifanzheng:${{ secrets.GITEE_ACCESS_TOKEN }}@$GITEE_REPO" main:main

